Add bids validation to integration tests
brown-bnc/xnat-tools pull request #109
Opened 2023-03-10 03:30 UTC by fordmcdonald

The main task of this PR was to add bids validation into our integration tests. I created a small utility function `validateBIDS()`, which writes the bids-validator output to a file (issues.txt).  From there, the function searches for "ERR" flags line by line, asserting that no errors have been raised. 

You'll notice I have added `skiplist = ["6"]` to many of the xnat2bids parameter lists.  This is due to the current BIDS specification does not support multiple echo T1w scans (https://github.com/bids-standard/bids-specification/issues/654).

2023-03-10 15:03 UTC, mirestrepo commented on tests/integration/test_postprocessing.py
> +def validateBIDS(bids_root_dir: str):
so far `bids-validator` wasn't a dependency of xnat-tools. This makes it one. How are you envisioning that?

2023-03-28 22:54 UTC, fordmcdonald commented
@mirestrepo I verified BIDS validation passed for multiple sessions of a given subject.  We can expand this test further to be more exhaustive across DEMODAT.  To trigger the job on  a merge to main, I added the following line `if: ${{ github.ref == 'refs/heads/main' }}` to the bids-validation job.  You can see above that the "Run system test for bids-validator" job was skipped on pull request.  Once you approve these changes, I can merge to main and validate the bids-validator job was successfully triggered.

2023-03-30 18:37 UTC, mirestrepo requested changes
This is basically done - but since we decided to install node and bids validator in the action (so only temporary in the runner), we don't need it in the docker image.

2023-03-30 18:37 UTC, mirestrepo commented on Dockerfile
> +RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
We are installing node in the action - so we don't need it baked into the docker image as well

2023-03-30 18:37 UTC, mirestrepo commented on Dockerfile
> +RUN npm install -g bids-validator
We are installing bids-validator in the action. We don't need it baked into the container.

We'll only need to do this if the action doesn't work

2023-03-30 20:03 UTC, mirestrepo approved these changes
Changes look good. 
You could though before merging, removing the `if: ${{ github.ref == 'refs/heads/main' }}`.. just to check that BIDS validation works... (and temporary you could add it to the tests to skip those) because otherwise, you'll need to fix the action by pushing to main which is more cumbersome. Once that passes, you can bring your statements back in order. I'm just not sure the setup node part will workout smoothly

2023-03-31 19:08 UTC, merged